FROM node:18.2-alpine

RUN apk add --no-cache \
  zip \
  git \
  bash


ENV TERRAFORM_VERSION 1.2.0

RUN wget -O terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
  unzip terraform.zip -d /usr/local/bin && \
  rm -f terraform.zip