---
- name: Create student user with password
  win_user:
    name: student
    password: std@TempPassword1!
    password_never_expires: yes
    groups:
      - Users
      - Remote Desktop Users
    state: present
