---
- name: Delete Amazon EC2 default scripts for setting wallpaper
  win_file:
    path: 'C:\ProgramData\Amazon\EC2-Windows\Launch\Module\Scripts\{{item}}'
    state: absent
  with_items:
    - "Clear-Wallpaper.ps1"
    - "Import-WallpaperUtil.ps1"
    - "New-WallpaperSetup.ps1"
    - "Set-Wallpaper.ps1"

- name: Make directory for wallpaper
  win_file:
    path: 'C:\wallpaper'
    state: directory

- name: Copy wallpaper to remote machine
  win_copy:
    src: "../../../../files/wallpaper.png"
    dest: 'C:\wallpaper\wallpaper.png'

- name: Set Wallpaper Wallpaper
  ansible.windows.win_powershell:
    script: |
      Set-ItemProperty -path 'HKCU:\Control Panel\Desktop\' -name Wallpaper -value "C:\wallpaper\wallpaper.png"
      Set-ItemProperty -path 'HKCU:\Control Panel\Desktop\' -name TileWallpaper -value "0"
      Set-ItemProperty -path 'HKCU:\Control Panel\Desktop\' -name WallpaperStyle -value "10" -Force
      RUNDLL32.EXE USER32.DLL,UpdatePerUserSystemParameters ,1 ,True

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install latest Python version
  win_chocolatey:
    name: python
    state: present

- name: Install Numpy
  ansible.windows.win_powershell:
    script: |
      pip install numpy

- name: Create directory for TightVNC setup file
  win_file:
    path: 'C:\TightVNC'
    state: directory

- name: Download TightVNC
  win_get_url:
    url: https://www.tightvnc.com/download/2.8.63/tightvnc-2.8.63-gpl-setup-64bit.msi
    dest: 'C:\TightVNC\TightVNC.msi'

- name: Install TightVNC
  win_package:
    path: 'C:\TightVNC\TightVNC.msi'
    state: present
    arguments:
      - /quiet
      - /norestart
      - ADDLOCAL=Server
      - SERVER_REGISTER_AS_SERVICE=1
      - SERVER_ADD_FIREWALL_EXCEPTION=1
      - SERVER_ALLOW_SAS=1
      - SET_POLLINGINTERVAL=1
      - VALUE_OF_POLLINGINTERVAL=5
      - SET_ALLOWLOOPBACK=1
      - VALUE_OF_ALLOWLOOPBACK=1
      - SET_RFBPORT=1
      - VALUE_OF_RFBPORT=5900
      - SET_USEVNCAUTHENTICATION=1
      - VALUE_OF_USEVNCAUTHENTICATION=1
      - SET_PASSWORD=1
      - VALUE_OF_PASSWORD=123

- name: Firewall rule to enable port 6080 for VNC WebSocket proxy
  win_firewall_rule:
    name: NoVNC Proxy
    localport: 6080
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Download Websockify
  ansible.windows.win_powershell:
    script: |
      git clone https://github.com/novnc/websockify.git 'C:\Websockify'

- name: Copy .bat file
  win_copy:
    src: "../../../files/websockify.bat"
    dest: 'C:\Websockify\run_websockify.bat'

- name: Schedule task
  win_scheduled_task:
    name: WebsockifyServer
    desciption: Run websockify server on startup (boot)
    actions:
      - path: cmd.exe
        arguments: /C C:\Websockify\run_websockify.bat
    triggers:
      - type: boot
    username: SYSTEM

- name: Install Edge
  win_chocolatey:
    name: microsoft-edge
    state: present

- name: Install Chrome
  win_chocolatey:
    name: googlechrome
    state: present

- name: Install 7zip
  win_chocolatey:
    name: 7zip
    state: present

- name: Schedule user data
  ansible.windows.win_powershell:
    script: 'C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 –Schedule'
