---
- name: update apt package listing
  ansible.builtin.shell: sudo apt update

- name: install XFCE desktop environment alongside gnome icon theme
  ansible.builtin.shell: sudo apt install xfce4 xfce4-goodies gnome-icon-theme -y

- name: install tigervnc
  ansible.builtin.shell: sudo apt install tigervnc-standalone-server

- name: Set password for VNC server
  ansible.builtin.expect:
    become: true
    become_user: student
    command: vncpasswd
    responses:
      Question:
        - testing@Password1
        - testing@Password1
        - n

- name: Set TigerVNC to use XFCE
  blockinfile:
    path: ~/.vnc/xstartup
    block: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4

- name: Set execute permissions for TigerVNC
  ansible.builtin.shell: chmod +x ~/.vnc/xstartup

- name: enable autorun of TightVNC Server
  ansible.builtin.lineinfile:
    path: ~/.vnc/xstartup
    line: exec /etc/X11/Xsession

- name: Set options for TigerVNC
  blockinfile:
    path: ~/.vnc/config
    block: |
      session=xfce
      geometry=1920x1080
      localhost
      alwaysshared

- name: Create Systemd file to autorun TigerVNC
  blockinfile:
    create: true
    path: /etc/systemd/system/vncserver@.service
    block: |
      [Unit]
      Description=TigerVNC Server
      After=network.target
      [Service]
      Type=simple
      ExecStart=/usr/bin/vncserver
      [Install]
      WantedBy=multi-user.target

- name: notify systemd with service
  ansible.builtin.shell: systemctl daemon-reload

- name: Start TigerVNC Server
  ansible.builtin.shell: systemctl start vncserver@:1.service
